### ISSUE TITLE
IDENTITY(1,1) and spaces

### ISSUE THREAD

**Issue by bazzilic** [bazzilic/PrismaDB-QueryParser#12]
As I understand, currently `IDENTITY(1,1)` has to be spelled exactly like that, i.e., not `IDENTITY ( 1 , 1 )` (with spaces) and not with other numbers for `seed` and `increment`. We need to fix this at some point (low priority).

https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql-identity-property

**Comment by cheziyi** [comment]
Remove `IDENTITY(1,1)`, and update grammer to comply with https://github.com/PrismaDB/PrismaDB/wiki/Data-Types

**Comment by cheziyi** [comment]
Done.
